package com.akgarg.apnagurukul.helper;

public class EmailMessages {

    public static String forgotPasswordOTPMessage(String toEmail,
                                                  String name,
                                                  String otp) {
        return "Dear " + "<strong>" + name + "</strong>," +
                "<br><br>" +
                "OTP to reset password of your account " + toEmail + " is " +
                "<strong>" + otp + "</strong>." +
                " Please use this otp to reset your password." +
                "<br><br>" +
                "Regards" +
                "<br>" +
                "SKAK (Team ApnaGurukul)" +
                "<br>" +
                "Proud Indian" +
                "<br><br>" +
                "<strong><p style=\"color: #7C6198;\">This email is automatically generated by the ApnaGurukul system. Please do not reply to this email.</p></strong>";
    }


    public static String registrationOTPMessage(String email,
                                                String name,
                                                int otp) {
        return "Dear " + "<strong>" + name + "</strong>," +
                "<br><br>" +
                "OTP to complete registration process of your account " + email + " is " +
                "<strong>" + otp + "</strong>. This OTP is valid for 5 minutes only. Please use this otp to complete the registration process." +
                "<br><br>" +
                "Regards" +
                "<br>" +
                "SKAK (Team ApnaGurukul)" +
                "<br>" +
                "Proud Indian" +
                "<br><br>" +
                "<strong><p style=\"color: #7C6198;\">This email is automatically generated by the ApnaGurukul system. Please do not reply to this email.</p></strong>";
    }


    public static String registrationSuccessMessage(String email,
                                                    String name) {
        return "Dear " + "<strong>" + name + "</strong>," +
                "<br>" +
                "Greetings from team ApnaGurukul!!" +
                "<br><br>" +
                "It is to inform you that your account with username " + email + " is " +
                "successfully registered and verified with us. We are delighted to have you with us here at ApnaGurukul." +
                "<br><br>" +
                "Have a happy and cheerful experience with us." +
                "<br><br>" +
                "Thanks" +
                "<br>" +
                "Regards" +
                "<br>" +
                "SKAK (Team ApnaGurukul)" +
                "<br>" +
                "Proud Indian" +
                "<br><br>" +
                "<strong><p style=\"color: #7C6198;\">This email is automatically generated by the ApnaGurukul system. Please do not reply to this email.</p></strong>";
    }


    public static String passwordSuccessfullyChangedMessage(String email,
                                                            String name) {
        return "Dear " + "<strong>" + name + "</strong>," +
                "<br><br>" +
                "Password of your account " + email + " is " +
                "successfully changed. Use your new credentials to login on our portal." +
                "<br><br>" +
                "If you have not perform this action, it means someone is trying to change your account password. " +
                "We recommend you to change your account password immediately" +
                "<br><br>" +
                "Regards" +
                "<br>" +
                "SKAK (Team ApnaGurukul)" +
                "<br>" +
                "Proud Indian" +
                "<br><br>" +
                "<strong><p style=\"color: #7C6198;\">This email is automatically generated by the ApnaGurukul system. " +
                "Please do not reply to this email.</p></strong>";
    }
}